runtime: nodejs20

env_variables:
  MONGO_URL: "mongodb+srv://urbannest:nXCsaqxZZPWzZub9@urbannest.xgowrux.mongodb.net/"
  JWT_SECRET: 1071054123
  NODE_EMAIL: saadankhalidaid07@gmail.com
  NODE_PASSWORD: 7rMZzURhj24a8Nmmcn
  PORT: 8000

instance_class: F2

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

readiness_check:
  app_start_timeout_sec: 600
